import esbuild from 'esbuild'
import process from 'process'
import { builtinModules } from 'node:module'
import fs from 'fs'
import path from 'path'
import os from 'os'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const outdir =
	'Aplicaciones/Obsidian/Pruebas/Pruebas/.obsidian/plugins/kanban-moonlight/'
const obsidianaPluginPath = path.join(os.homedir(), outdir)

const copyToOutdir = () => {
	const filesToCopy = ['main.js', 'manifest.json', 'styles.css']

	for (const file of filesToCopy) {
		fs.copyFileSync(
			path.resolve(file),
			path.resolve(obsidianaPluginPath, file),
		)
	}
}

const copyToOutdirPlugin = {
	name: 'copy-to-outdir',
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length === 0) {
				copyToOutdir()
			}
		})
	},
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [copyToOutdirPlugin],
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
	fs.watch('styles.css', () => {
		copyToOutdir()
	})
}
